import * as THREE from 'three';
import { nativeObject } from '../rotation/render-context';

type Own = <T extends { dispose(): void }>(value: T) => T;

/** Copy resources visible to the camera layers, without culling any rotation angle. */
export function copyPageResources(root: THREE.Scene, camera: THREE.Camera, own: Own): void {
  const geometries = new Map(), textures = new Map(), materials = new Map();
  const hidden = () => { const material = own(new THREE.MeshBasicMaterial()); material.visible = false; return material; };
  const texture = (input: any, path: string) => {
    const source = nativeObject(input);
    if (textures.has(source)) return textures.get(source);
    if (source.isRenderTargetTexture || source.isDepthTexture || source.isFramebufferTexture || source.isExternalTexture) {
      throw new Error(`${path} 使用仅存在于网页 GPU 的纹理，无法直接复制到离屏上下文`);
    }
    const result = own(source.clone());
    textures.set(source, result);
    return result;
  };
  // Uniform structs/arrays may contain textures at arbitrary depths. Three's default
  // cloneUniforms only handles top-level textures and may retain nested page objects.
  const uniform = (input: any, path: string, seen = new Map()): any => {
    const value = nativeObject(input);
    if (!value || typeof value !== 'object') return value;
    if (value.isTexture) return texture(value, path);
    if (seen.has(value)) return seen.get(value);
    if (ArrayBuffer.isView(value)) return (value as any).slice ? (value as any).slice() : new DataView(value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength));
    if (value instanceof ArrayBuffer) return value.slice(0);
    for (const kind of ['Color', 'Vector2', 'Vector3', 'Vector4', 'Matrix3', 'Matrix4', 'Quaternion']) {
      if (value['is' + kind]) return new (THREE as any)[kind]().copy(value);
    }
    const result: any = Array.isArray(value) ? [] : {};
    seen.set(value, result);
    for (const key of Object.keys(value)) result[key] = uniform(value[key], `${path}.${key}`, seen);
    return result;
  };
  const material = (input: any, nodeName: string): THREE.Material => {
    const source = nativeObject(input);
    if (!source?.isMaterial) throw new Error(`${nodeName} 缺少有效材质`);
    if (materials.has(source)) return materials.get(source);
    // Explicit page wireframe overlays are replaced by our own optional wire pass.
    if (!source.visible || source.userData?.wireframe === true) {
      const result = hidden(); materials.set(source, result); return result;
    }
    const label = `节点“${nodeName}”材质“${source.name || source.type}”`;
    let result: any;
    if (source.isShaderMaterial || source.isRawShaderMaterial) {
      result = own(source.isRawShaderMaterial ? new THREE.RawShaderMaterial() : new THREE.ShaderMaterial());
      // Avoid page constructors, patched clone methods, implicit uniform texture
      // copies and circular application userData. Shader code/defines are retained.
      result.copy({ ...result, ...source, uniforms: {}, uniformsGroups: [], userData: {} });
      result.defaultAttributeValues = uniform(source.defaultAttributeValues || result.defaultAttributeValues, `${label}.defaultAttributeValues`);
      result.index0AttributeName = source.index0AttributeName;
      result.uniforms = uniform(source.uniforms, `${label}.uniforms`);
      result.uniformsGroups = (source.uniformsGroups || []).map((group: any) => {
        const copy = own(new THREE.UniformsGroup()).setName(group.name).setUsage(group.usage);
        copy.uniforms = group.uniforms.map((entry: any) => Array.isArray(entry)
          ? entry.map(item => new THREE.Uniform(uniform(item.value, `${label}.uniformsGroups`)))
          : new THREE.Uniform(uniform(entry.value, `${label}.uniformsGroups`)));
        return copy;
      });
    } else {
      result = own(source.clone());
    }
    for (const [key, value] of Object.entries(source) as any) if (value?.isTexture) {
      // Standard material environment maps are regenerated by the offscreen studio.
      result[key] = key === 'envMap' && value.isRenderTargetTexture && !source.isShaderMaterial
        ? null : texture(value, `${label}.${key}`);
    }
    materials.set(source, result);
    return result;
  };
  root.traverseVisible((node: any) => {
    if (!node.material) return;
    if (!node.layers.test(camera.layers)) { node.material = hidden(); return; }
    node.material = Array.isArray(node.material)
      ? node.material.map(value => material(value, node.name || node.type)) : material(node.material, node.name || node.type);
    const visible = (Array.isArray(node.material) ? node.material : [node.material]).some(value => value.visible);
    if (visible && node.geometry) {
      if (!geometries.has(node.geometry)) geometries.set(node.geometry, own(node.geometry.clone()));
      node.geometry = geometries.get(node.geometry);
    }
  });
}
